import { jsPDF } from "jspdf";
import autoTable, { type RowInput } from "jspdf-autotable";
import { formatCurrency, formatDate } from "@/lib/utils";

export type PayslipData = {
  companyName: string;
  companyAddress?: string | null;
  period: string;
  employee: {
    fullName: string;
    nik: string;
    department: string;
    position: string;
  };
  basicSalary: number;
  allowances: number;
  deductions: number;
  lateDays: number;
  unpaidLeaveDays: number;
  netSalary: number;
  currency: string;
  generatedAt: Date;
};

export function buildPayslipPdf(data: PayslipData): Uint8Array {
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const marginX = 40;
  doc.setFontSize(18);
  doc.text(data.companyName, marginX, 50);
  doc.setFontSize(10);
  if (data.companyAddress) doc.text(data.companyAddress, marginX, 66);
  doc.setFontSize(14);
  doc.text("PAYSLIP", marginX, 100);
  doc.setFontSize(10);
  doc.text(`Period: ${data.period}`, marginX, 118);
  doc.text(`Generated: ${formatDate(data.generatedAt, true)}`, marginX, 132);

  autoTable(doc, {
    startY: 150,
    theme: "plain",
    styles: { fontSize: 10 },
    body: [
      ["Employee", data.employee.fullName],
      ["NIK", data.employee.nik],
      ["Department", data.employee.department],
      ["Position", data.employee.position],
    ] as RowInput[],
    columnStyles: { 0: { fontStyle: "bold", cellWidth: 100 } },
  });

  const lastY1 = (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY;
  autoTable(doc, {
    startY: lastY1 + 20,
    head: [["Description", "Amount"]],
    body: [
      ["Basic Salary", formatCurrency(data.basicSalary, data.currency)],
      ["Allowances", formatCurrency(data.allowances, data.currency)],
      [`Deductions (${data.lateDays} late, ${data.unpaidLeaveDays} unpaid days)`, "- " + formatCurrency(data.deductions, data.currency)],
      [
        { content: "Net Salary", styles: { fontStyle: "bold" } },
        { content: formatCurrency(data.netSalary, data.currency), styles: { fontStyle: "bold" } },
      ],
    ] as RowInput[],
    headStyles: { fillColor: [15, 23, 42] },
    styles: { fontSize: 10 },
    columnStyles: { 1: { halign: "right" } },
  });

  const lastY2 = (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY;
  doc.setFontSize(8);
  doc.setTextColor(120);
  doc.text(
    "This payslip is generated by HRMS. For any questions please contact your HR department.",
    marginX,
    lastY2 + 30
  );

  const arrayBuffer = doc.output("arraybuffer");
  return new Uint8Array(arrayBuffer);
}

export type ReportTable = {
  title: string;
  subtitle?: string;
  columns: string[];
  rows: (string | number)[][];
  meta?: Record<string, string>;
};

export function buildReportPdf(report: ReportTable, companyName: string): Uint8Array {
  const doc = new jsPDF({ unit: "pt", format: "a4", orientation: "landscape" });
  const marginX = 40;
  doc.setFontSize(16);
  doc.text(companyName, marginX, 40);
  doc.setFontSize(13);
  doc.text(report.title, marginX, 60);
  if (report.subtitle) {
    doc.setFontSize(10);
    doc.text(report.subtitle, marginX, 76);
  }
  let metaY = 92;
  if (report.meta) {
    doc.setFontSize(9);
    for (const [k, v] of Object.entries(report.meta)) {
      doc.text(`${k}: ${v}`, marginX, metaY);
      metaY += 12;
    }
  }
  autoTable(doc, {
    startY: metaY + 10,
    head: [report.columns],
    body: report.rows as RowInput[],
    headStyles: { fillColor: [15, 23, 42] },
    styles: { fontSize: 9 },
  });
  const arrayBuffer = doc.output("arraybuffer");
  return new Uint8Array(arrayBuffer);
}
